# Generated by Django 4.2.1 on 2023-09-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL('CREATE SCHEMA test_app;'),
        migrations.CreateModel(
            name="TestUserModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("email", models.CharField(unique=True)),
                ("password", models.CharField()),
            ],
            options={
                "db_table": 'test_app"."test_user',
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TestUserTypeModel",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(unique=True)),
                ("description", models.CharField()),
            ],
            options={
                "db_table": 'test_app"."test_user_type',
                "ordering": ["id"],
            },
        ),
    ]
