# Generated by Django 4.2.1 on 2023-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL('CREATE SCHEMA test_app_outro;'),
        migrations.CreateModel(
            name="TestUserOutroModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name_outro", models.CharField()),
                ("email_outro", models.CharField(unique=True)),
                ("password_outro", models.CharField()),
            ],
            options={
                "db_table": 'test_app"."test_user_outro',
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TestUserTypeOutroModel",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("type_outro", models.CharField(unique=True)),
                ("description_outro", models.CharField()),
            ],
            options={
                "db_table": 'test_app"."test_user_type_outro',
                "ordering": ["id"],
            },
        ),
    ]
